config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :show, :index, :edit, :update]  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200}
end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy  
  
  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: { maximum: 50}
  
 

has_one_attached :profile_image

def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id) 
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @books = Book.new
  end

   def create
    @user = current_user
    @book = Book.new(books_params)
    @book.user_id = (current_user.id)
    if @book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)

    else
    @books = Book.all.order(id: :asc)

    render :index
   end
   end

  def index
    @user = current_user
    @books = Book.page(params[:page])
    @book = Book.new
  end

  def show
    @user = current_user
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @books = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(books_params)
    flash[:notice] = "You have created book successfully."
    redirect_to book_path(book.id)

    else
    @books = Book.all
    flash[:notice]= 'errors prohibited this obj from being saved.'
    render "edit"
    end

  end

  def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to "/books"
  end

  private

  def books_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
        params.require(:user).permit(:name,:profile_image,:introduction)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
  
  def about
  
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  
 
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
  end
  
  def new
    @user = User.new(user_params)
        if @user.save
         flash[:notice] = "You have created user successfully."
         redirect_to  user_path(current_user.id)
        else
         flash[:notice]= 'errors unable to register new user.'
         render "users/sign_up"
        end
  end  
  
  
  
  def index
    @users =User.all
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update  
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:notice] = " errors prohibited this obj from being saved:"
          render :edit
  end
 end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless user.id == current_user.id 
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class= "col-md-3">
<h2>User info</h2>
<table>

  <p><%= image_tag @user.get_profile_image(100,100) %></p>

  <tr><th><h4>name</h4></th>
   <th><%= @user.name %></th></tr>

  <tr><th><h4>introduction</h4></th>
  <th><%= @user.introduction %></th></tr>
  <tr><th><%= link_to edit_user_path(@user.id), class:"nav-link" do %>
  <i class="fa-solid fa-user-gear"></i>
  <% end %>
  </th></tr>
  </table>

  <%#投稿画面 %>
  <%= form_with model: Book.new do |f| %>

<h1>New book</h1>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <nav>
  <%= f.submit 'Create Book' %>
  </nav>
<% end %>
</div>

app/views/books/edit.html.erb
<div class="box2">

<h1>Editing Book</h1>
<%= form_with model: @books do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title,class:"col-xs-12" %>
    <h4>Opinion</h4>

    <%= f.text_area :body,class:"col-xs-12" %>

  <nav>
     <%= f.submit 'Update Book',class: "col-xs-12 btn btn-primary" %>
  </nav>
　<% end %>

<%= link_to "Show",book_path(@books.id)%>
<%= link_to "Back",books_path %>

</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="row">

<%= render 'list', book: @book, books: @books %>
<%#一覧画面 %>
<div class= "col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
<tr>
<th></th>  
<th><p>Title</p></th>
<th><p>Opinion</p></th>
<th colspan= "3"></th>
</tr>

<% @books.each do |book| %>


<tr>
  <%= link_to books_path do %>
  <% end %>

  <th><%= image_tag book.user.get_profile_image(100,100) %></th>
  <th><%=link_to book.title, book_path(book.id)%></th>
  <th><%= book.body %></th>
  </tr>
  <% end %>
  
  </table>
  </div>
  </div>
  </div>

app/views/books/new.html.erb
<div>
  <%= flash[:notice] %>
</div>
<%= form_with model: @books do |f| %>
<h1>New books</h1>

  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
  <div class="container px-5 px-sm-0">
  <div class="row">
    
  <%= render 'list', book: @book, books: @books %>
  
  <div class= "col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table table-striped">
  <th><td><p><%= image_tag @book.user.get_profile_image(100,100) %></p>
  <p><%= link_to @book.user.name, user_path(@book.user_id) %></p></td></th>
  <td><p><%= link_to @book.title, book_path(@book.id)%></p></td>
  <td><p><%= @book.body %></p></td>
  
  <% if @book.user_id == current_user.id %>
  <% end %>
  
  <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
  <td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
  </tr>
  </table>
  </div>
  </div>
  </div>
  
  

app/views/homes/about.html.erb
<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers !!</strong></h1>
<p>In<i class="fa-solid fa-book"></i><strong>Bookers,</strong></p>
<div class="btn-wrapper col-10 mx-auto">
</div>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
<div class="row">
<div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            


<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers !!</strong></h1>
<p>In<i class="fa-solid fa-book"></i><strong>Bookers,</strong></p>
    
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>

<div class="btn-wrapper col-10 mx-auto">
<div class="row">
<a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a></div>

<div class="row">
<a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a></div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<div class="box">
<!DOCTYPE html>
<html>
<head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/caae059452.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
    <nav class="navbar navbar-expand-md navbar-dark text-white bg-dark ">

    <span><%= link_to "Bookers",root_path, class:"nav-link text-light" %></span>


    <ul class= "navbar-nav ml-auto" >
      <% if user_signed_in? %>

    <li><%= link_to user_path(current_user.id), class:"nav-link text-light" do %>
          <i class="fas fa-home"></i>Home
        <% end %>
    </li>
    <li><%= link_to users_path, class:"nav-link text-light" do %>
          <i class="fa-solid fa-link"></i>Users
        <% end %>
    </li>
    <li><%= link_to books_path, class:"nav-link text-light" do %>
          <i class="fa-solid fa-user-plus"></i>Books
         <% end %>
    </li>
    <li><%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
          <i class="fa-solid fa-right-to-bracket"></i>Log out
         <% end %>
    </li>

    <% else %>
    <li><%= link_to root_path, class:"nav-link text-light" do %>
          <i class="fa-solid fa-house"></i>Home
          <% end %>
    </li>
    <li><%= link_to about_path, class:"nav-link text-light" do %>
          <i class="fa-solid fa-link"></i>About
          <% end %>
    </li>
    <li><%= link_to "/users/sign_up", class:"nav-link text-light" do %>
          <i class="fa-solid fa-user-plus"></i>Sign up
          <% end %>
    </li>
    <li><%= link_to "/users/sign_in", class:"nav-link text-light" do %>
          <i class="fa-solid fa-right-to-bracket"></i>Log in
          <% end %>
    </li>

   

    <% end %>
    </ul>
    </nav>
    </div>

   </header>


  <main>
  <div>
      <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    </div>
    <%= yield %>
    </main>

    <footer>
    <div class="container mt-5">
    <div class='row'>
    <div class='mx-auto'>
    <p>CopyRight Infratop.inc</p>
    </div>
    </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name %>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_field :introduction %>
  
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
  <div class="container px-5 px-sm-0">
  <div class="row">
    
  <%= render 'books/list', book: @book, books: @books %>
  
  <div class= "col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class='table'>
    <tr>
    <th>Image</th>
    <th>Name</th>
    </tr>

    <% @users.each do |users| %>
    <tr>
   <th><%= image_tag users.get_profile_image(100,100) %></th>
   <th><%= users.name %><th>
   <th><%= link_to "Show",user_path(users.id) %></th>
   </tr>
   <% end %>
   </table>
  </div>
  </div>
  </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<%= render 'books/list', book: @book, books: @books %>

<div class= "col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table">
<tr>
<th></th>  
<th>Title</th>
<th>Opinion</th>
<th colspan= "3"></th>
</tr>

<% @books.each do |book| %>
  
  <tr>
  <%= link_to book_path(book.id) do %>
  <% end %>
  
  <th><%= image_tag book.user.get_profile_image(100,100) %></th>
  <th><%=link_to book.title, book_path(book.id) %></th>
  <th><%= book.body %></th>
  </tr>
<% end %>
  
  </table>
  </div>
  </div>
  </div>